### ISSUE TITLE
Modal Background color change

### ISSUE THREAD

**Issue by adityakoushik** [elrumordelaluz/reactour#13]
I wanna change modal background color to white background color,Like background-color: rgba(1,1,1,.7) to background-color: rgba(1,1,1,-0.03).
Please help me asap,Thank you

**Comment by elrumordelaluz** [comment]
You could user the prop `maskClassName` to overrides the _Mask_ styles.

Something like this, in the _Component_: 
```js
<Tour
  onRequestClose={}
  steps={[…]}
  isOpen={true}
  maskClassName="myMask"
/>
```

and in your stylesheet:
```css
.myMask {
  background-color: rgba(255,255,255,.3)
}
```
