### ISSUE TITLE
Centering the Nav Arrow and Dots

### ISSUE THREAD

**Issue by bmoquist** [elrumordelaluz/reactour#47]
Hello -- Is there a trick to centering the navigation arrows and dots into the middle of the tour guide helper? They are currently left aligned, which looks awkward if there are not a large number of steps in the tour.

In Chrome's inspector, the following does the trick: 
```css
margin-left: 0;
margin-right: 0;
justify-content: 'center';
```
I don't seem to be able to pass this through the className prop to impact the div.

Any suggestions/help would be great!

**Comment by elrumordelaluz** [comment]
@bmoquist updating into `v1.8.0` you now should be able to style some elements through the added `data-tour-elem` attribute.

In your case should be:

```css
[data-tour-elem="controls"]: {
  justify-content: center;
}
```

Let me know if it works for you.

**Comment by bmoquist** [comment]
Thanks much -- works perfectly!

**Comment by kid-three** [comment]
Where would you put this exactly?

**Comment by elrumordelaluz** [comment]
Sorry @dannyvin72, updated the [snippet](https://github.com/elrumordelaluz/reactour/issues/47#issuecomment-384922774). This is just `css`, you could paste in your own stylesheet.

```css
[data-tour-elem="controls"] {
  justify-content: center;
}
```
