### ISSUE TITLE
Arrow demo does not work

### ISSUE THREAD

**Issue by elixiao** [elrumordelaluz/reactour#492]
the [arrow demo](https://reactour.vercel.app/) is broken using version 3.x.

<img width="758" alt="image" src="https://user-images.githubusercontent.com/2291033/186614634-74b53fce-51b6-4970-b464-c03ce123dac2.png">

I think it's caused by @reactour/mask or @reactour/popover dependency.  After lock version manually in package.json resolutions field it works well:

```
"resolutions": {
  "@reactour/mask": "0.5.1",
  "@reactour/popover": "0.5.0"
},
```

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/2291033/186616200-27f0e9b4-9f48-4240-ac94-265b8705cfc1.png">

But downgrade @reactour/tour to version 2.x still not work because it's dependency version is `*`

<img width="707" alt="image" src="https://user-images.githubusercontent.com/2291033/186614030-f9835976-1de0-48a2-9028-46bedd98c81a.png">

**Comment by elixiao** [comment]
Why not lock @reactour/tour dependency versions in package.json? 
This leads to my previous code is broken after upgrade to 3.x and still not work after downgrade to 2.x...

**Comment by elrumordelaluz** [comment]
Hi @elixiao, thanks for open the _Issue_ and to catch this specific use-case!

Since `v3` @reatour/* packages doesn't use anymore a css-in-js lib (that was emotion). This results in that there is no more need to install this lib as `peerDep` and there is also a reduced bundle size. This lib was used for really tiny but handy peaces of code, like style pseudo elements using dynamic values. That is the case for the `:after` element in the arrow example. I am adding `classNames` (so
![Screenshot 2022-08-25 at 12 15 15](https://user-images.githubusercontent.com/784056/186639181-1d01a614-8dfa-4897-b312-95c2335b9296.png)
on will update docs) that will be useful, to override styles on user-land, and helps as to solve those situations (like pseudo-elements and pseudo-classes) using `--css-variables`.

Here is the [updated demo](https://reactour.vercel.app/popover) which is using the last version of `@reactour/popover`.

**Comment by elixiao** [comment]
@elrumordelaluz I didn't know that variables can be used in this way. Before you told me I use another hack solution:

```js
const stepArrowDirections = ['bottom', 'right', 'left', 'top']
function ContentComponent(props) {
  const { currentStep, steps, setIsOpen, setCurrentStep } = props
  const isLastStep = currentStep === steps.length - 1
  const content = steps[currentStep].content
  
  return (
    <div className={`user-guide-content ${stepArrowDirections[currentStep]}-arrow`}>
       // code here
    </div>
  )
}
const props = {
  steps,
  ContentComponent, // this is the crucial point
  className: 'user-guide',
  styles: {
    popover: (base, state) => {
      return {
        ...base,
        // ...doArrow(state.position, state.verticalAlign, state.horizontalAlign), // do not work here
      }
    },
    maskArea: (base) => ({ ...base, rx: 5 }),
  },
}
export default function ({ children }) {
  return <TourProvider {...props}>{children}</TourProvider>
}
```

my css is:

```css
.user-guide-content {
  &::after {
    content: '';
    width: 0;
    height: 0;
    position: absolute;
  }

  &.bottom-arrow::after {
    border-left: 8px solid transparent;
    border-right: 8px solid transparent;
    border-bottom: 12px solid white;
    left: 22px;
    top: -10px;
  }
  &.right-arrow::after {
    border-top: 8px solid transparent;
    border-bottom: 8px solid transparent;
    border-right: 12px solid white;
    top: 22px;
    left: -10px;
  }

  &.left-arrow::after {
    border-top: 8px solid transparent;
    border-bottom: 8px solid transparent;
    border-left: 12px solid white;
    top: 22px;
    right: -10px;
  }

  &.top-arrow::after {
    border-left: 8px solid transparent;
    border-right: 8px solid transparent;
    border-top: 12px solid white;
    left: 22px;
    bottom: -10px;
  }
}
```

Obviously, CSS variable solution is better than mine. It's great and I will use it. Thank you very much.
